name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Secrets
        run: |
          echo "Checking if secrets are configured..."
          
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "❌ EC2_HOST is NOT set"
          else
            echo "✅ EC2_HOST is set: ${{ secrets.EC2_HOST }}"
          fi
          
          if [ -z "${{ secrets.EC2_USER }}" ]; then
            echo "❌ EC2_USER is NOT set"
          else
            echo "✅ EC2_USER is set: ${{ secrets.EC2_USER }}"
          fi
          
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "❌ EC2_SSH_KEY is NOT set"
          else
            echo "✅ EC2_SSH_KEY is set (length: ${#EC2_SSH_KEY})"
          fi
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
